### ISSUE TITLE
Specific Django version in requirements.txt

### ISSUE THREAD

**Issue by illagrenan** [bbengfort/django-generic-json-views#10]
Hi, first of all thanks for this package.

When I run `pip install django-generic-json-views` it will install specific Django version (it is pinned in https://github.com/bbengfort/django-generic-json-views/blob/master/requirements.txt#L2). But this will break my existing `venv`, I have to keep Django `1.6.x` branch.

In my opinion it is good practice to have min and max versions of required packages, e.g. https://github.com/pennersr/django-allauth/blob/master/setup.py#L124.

**Comment by bbengfort** [comment]
Yep, sorry about that - I usually just quickly `pip freeze > requirements.txt` as I'm messing with dependencies and that blew up the greater than 1.5 dependency. I'll make the fix. 

In the future - feel free to submit a pull request, especially for a one-liner! You'll be a contributor to the code, and I'll only have to press a button to fix things! 

Along those lines - please note that I haven't managed to get the testing for Django 1.5-1.6 running (it's tested on Django 1.7). This is due to the testing package, not necessarily whether it works on older versions of Django. If you could assist me in getting tests working for Django 1.6 - I'd appreciate it! (Let me know if you're willing, and I can point out where I think things are going wrong, I think I've already put up an issue for it). 

Thanks again!

**Comment by bbengfort** [comment]
Ok, it's up and in PyPi - though for some reason it's taking a bit to sync. You should be able to fetch the code directly and `python setup.py install` and you'll avoid the issues with the Django update.
